name: Add to Firebase App Distribution

on:
  push:
    branches: [ v2 ]

jobs:
  distribute:
    runs-on: macos-latest

    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v4
    
      - name: Setup Bun Runtime ðŸž
        uses: antongolub/action-setup-bun@v1
        with:
          bun-version: latest
          bun-repo: 'Jarred-Sumner/bun-releases-for-updater'
          bun-config: '{"install": {"production": false}}'
          cache: true
          cache-bin: true
          
      - name: Cache node modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
            path: node_modules
            key: bun-${{ hashFiles('bun.lockb') }}

      - name: Install node modules if cache not present ðŸ“¦
        run: bun i --immutable
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - name: Create Keystore file ðŸ”‘
        run: |
            echo "$RELEASE_KEYSTORE_CONTENT" > release-keystore.b64
            base64 -d -i release-keystore.b64 > android/app/release.keystore
        env:
            RELEASE_KEYSTORE_CONTENT: ${{ secrets.RELEASE_KEYSTORE_CONTENT }}  

      - name: Create Google Service Credentials file ðŸ”‘
        run: |
            echo "$GOOGLE_SERVICES" > google-services.json.b64
            base64 -d -i google-services.json.b64 > android/app/google-services.json
        env:
            GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}  
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
            distribution: zulu
            java-version: 11
            cache: 'gradle'
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.RELEASE_KEYSTORE_CONTENT }}
          alias: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          
      - name: Build release 
        run: |
          ls -la
          cd android
          ./gradlew clean
          ./gradlew assembleRelease
          cd app/build/outputs/apk/release
          ls -la
      
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{secrets.FIREBASE_APP_ID}}
            serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS_CONTENT }}
            groups: testers
            file: android/app/build/outputs/apk/release/app-release.apk
            debug: true
        env:
            FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
            FIREBASE_CREDENTIALS_CONTENT: ${{ secrets.FIREBASE_CREDENTIALS_CONTENT }}
          