name: Android Distribution

on:
  push:
    branches: [ v2 ]

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v4
    
      - name: Setup Bun Runtime ðŸž
        uses: antongolub/action-setup-bun@v1
        with:
          bun-version: latest
          bun-repo: 'Jarred-Sumner/bun-releases-for-updater'
          bun-config: '{"install": {"production": false}}'
          cache: true
          cache-bin: true
          
      - name: Cache node modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
            path: node_modules
            key: bun-${{ hashFiles('bun.lockb') }}

      - name: Install node modules if cache not present ðŸ“¦
        run: bun i --immutable
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - name: Create credential files ðŸ”‘
        run: |
            echo "${{ secrets.GOOGLE_SERVICES }}" > google-services.json.b64
            base64 -d -i google-services.json.b64 > android/app/google-services.json

            echo "${{ secrets.GRADLE_PROPERTIES_CONTENT }}" > gradle.properties.b64
            base64 -d -i gradle.properties.b64 > android/app/gradle.properties
      
      - name: Set up JDK 11 â˜•
        uses: actions/setup-java@v3
        with:
            distribution: zulu
            java-version: 11
            cache: 'gradle'
          
      - name: Build APK ðŸ—ï¸
        run: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease

      - name: Check if APK exists ðŸ“‚
        run: |
          ls -la
          cd android/app/build/outputs/apk/release
          find . -type d -print

          if [ ! -f app-release.apk ]; then
            echo "ðŸ”´ File not found!"
            exit 1
          fi

      - name: Upload to Firebase App Distribution ðŸ“²
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{ secrets.FIREBASE_APP_ID }}
            serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS_CONTENT }}
            groups: testers
            file: android/app/build/outputs/apk/release/app-release.apk
            debug: true
        env:
            FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
            FIREBASE_CREDENTIALS_CONTENT: ${{ secrets.FIREBASE_CREDENTIALS_CONTENT }}
      
      - name: Set Last Action Time
        id: set_last_action_time
        run: echo "::set-output name=time::$(date -u +%Y-%m-%dT%H:%M:%SZ)"
      - name: Store Last Action Time
        run: echo "LAST_ACTION_TIME=${{ steps.set_last_action_time.outputs.time }}" >> $GITHUB_ENV          